FROM node:20-alpine

WORKDIR /app

# Copy app files
COPY dist dist/
COPY server.js .

# Expose port
EXPOSE 8080

# Set environment
ENV NODE_ENV=production
ENV PORT=8080

# Start server
CMD ["node", "server.js"]
